# Generated by Django 2.0.5 on 2019-05-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('in_stock', models.IntegerField()),
                ('valoration', models.IntegerField()),
                ('description', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=250)),
                ('product_type', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_with_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('extra_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Category'),
        ),
    ]
