# Generated by Django 2.0.5 on 2019-05-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190503_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='extrainformation',
            old_name='extra_information',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='extrainformation',
            name='upc',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
